<?php require('template/header.phtml');
?>
<body data-hijacking="on" data-animation="gallery" onwheel="mouseScroll(event)">
<main>
    <div class = "first-screen" id="first-screen">
        <div class="empty">
        </div>
        <div id= "title">
            <h1 class="main-title" id= "main-title">
               Vadims Seimanovs
            </h1>
        </div>
        <div id = "main-text">
            <p>
                Hello, my name is Vadims Seimanovs. I am a software/web developer.
            </p>
        </div>
        <div id = "picture-one">
            <img src="/images/TheCodeIsFuture.jpg" alt="code-img">
        </div>
        <div id="picture-two">
            <img src="/images/RubiksCube.png" alt="cube">
        </div>
        <div id="underline-img">
            <img class= "background-image" src="/images/AboutMe.png" alt="Outline">
        </div>
    </div>
    <div class = "second-screen" id="second-screen">
        <div class = "second-title-module">
            <div id = "second-title">
                <a href="#second-screen">
                    <button id = "about-title">
                        ABOUT ME
                    </button>
                </a>
            </div>
        </div>
        <div id = "about-me">
            <p>
                I have graduated University of Salford with 2.1 degree classification. I am passioned about programming and video games, combining two of my passiones creates something unique that allows me to make something that will draw peoples attentions.
            </p>
        </div>
        <div id = "about-me-pic">
            <img id="pic" src="/images/mypic.JPG" alt="pic-of-me">
        </div>
    </div>
    <div class = "third-screen" id="third-screen">
        <div class = "projects-title-module">
            <div id="project-title-wrap">
                <a href="#third-screen">
                    <button id = "project-title">
                        Projects
                    </button>
                </a>
            </div>
        </div>
        <div id = "first-project-module">
            <div id="first-project-wrap">
                <header class = "project-header">
                    Campsite Website MVC
                </header>
                <p class = "project-text">
                    Camspite website is the prject that have been created for one of the university assgnment. Campsite website includes the use of different API one of which is Google maps to locate the possible camping sites for the people to visit. Overlall website comes with the user profiles, admin panles and different uses of SQL database to store the information.
                </p>
                <div class="project-date" id="first-date">
                    <p class="p-date">
                        20.04.2019
                    </p>
                </div>
                <div class = "project-lang" id = "second-first-lang">
                    <p class = "p-lang">
                        SQL
                    </p>
                </div>
                <div class = "project-lang" id = "second-second-lang">
                    <p class = "p-lang">
                        JavaScript
                    </p>
                </div>
                <div class = "project-lang" id = "second-third-lang">
                    <p class = "p-lang">
                        PHP
                    </p>
                </div>
            </div>
        </div>
        <div id = "second-project-module">
            <div id = "second-project-wrap">
                <header class = "project-header">
                    Android Game
                </header>
                <p class = "project-text">
                    Android development gave me much more then learning Java programming language but also gave me experience of using Android Studio and
                </p>
                <div class="project-date" id="second-date">
                    <p class="p-date">
                        12.03.2020
                    </p>
                </div>
                <div class = "project-lang" id = "first-lang">
                    <p class = "p-lang">
                        Java
                    </p>
                </div>
            </div>
        </div>
        <div id = "third-project-module">
            <div id="third-project-wrap">
                <header class = "project-header">
                    3D Games Unity + Unreal Engine
                </header>
                <p class = "project-text">
                    For my final year project I have developed two games that are similar to each other. The main objective of dissertation was to outline the differences between two game engines and see how the development diffiers using one or another game engine.
                </p>
                <div class="project-date" id="third-date">
                    <p class="p-date">
                        25.03.2020
                    </p>
                </div>
                <div class = "project-lang" id = "second-first-lang">
                    <p class = "p-lang">
                        C#
                    </p>
                </div>
                <div class = "project-lang" id = "second-second-lang">
                    <p class = "p-lang">
                        Blueprints
                    </p>
                </div>
            </div>
        </div>
        <div id="project-img">
            <img src="/images/Project.png" alt="Projects">
        </div>
    </div>
    <div class = "sixth-screen" id="sixth-screen">
        <div class = "top-image">
            <img src="/images/Contact.png" alt="top-image" class="contact-img">
        </div>
        <div class = "achievements-title-module">
            <div id="achievements-title-wrap">
                <a href="#sixth-screen">
                    <button id = "achievements-title">
                        Achievements
                    </button>
                </a>
            </div>
        </div>
        <div id = "p-achievements">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent risus libero, posuere eu interdum nec, commodo non eros. Donec tincidunt risus in eleifend maximus. Ut bibendum sit amet massa sed auctor. Duis in neque non ipsum eleifend laoreet. Curabitur volutpat maximus metus, ut gravida est pellentesque sit amet.
            </p>
        </div>
        <div id = "achievements-pic">
            <img src="/images/achievements.png" alt="Hack-win">
        </div>
    </div>
    <div class = "fourth-screen" id="fourth-screen">
        <div class = "contact-title-module">
            <div id="contact-title-wrap">
                <a href="#fourth-screen">
                    <button id = "contact-title">Contact</button>
                </a>
            </div>
        </div>
        <div id = "linkedIn-profile">
            <div class="LI-profile-badge"  data-version="v1" data-size="large" data-locale="en_US" data-type="horizontal" data-theme="dark" data-vanity="vadims-seimanovs"><a class="LI-simple-link" href='https://uk.linkedin.com/in/vadims-seimanovs?trk=profile-badge'>Vadims Seimanovs</a></div>
        </div>
        <div id = "twitter-img">
            <a href="https://twitter.com/TheWereWo1f">
                <img src="/images/Twitter.png" alt="Twitter-logo">
            </a>
        </div>
        <div id = "email-img">
            <a href="mailto:vadims.seimanovs@gmail.com">
                <img src="/images/Gmail.png" alt="email-logo">
            </a>
        </div>
        <div id = "github-profile">
            <div class="github-card" data-github="VadimsSeimanovs" data-width="400" data-height="150" data-theme="default"></div>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
    <script src="/js/scroll.js"></script>
    <script src="/js/style.js"></script>
    <script>
        $(document).ready(function(){
            $("a").on('click', function(event) {
                if (this.hash !== "") {
                    event.preventDefault();
                    var hash = this.hash;
                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 800, function(){
                        window.location.hash = hash;
                    });
                }
            });
        });
    </script>
</main>
</body>
<?php require('template/footer.phtml');
?>
