<?php require('template/header.phtml');
?>
<main>
    <div class = "first-screen">
        <div id= "title">
            <header id= "main-title">Vadims Seimanovs</header>
        </div>
        <div id = "main-text">
            <p>
                Hello, my name is Vadims Seimanovs. I am a software/web developer.
            </p>
        </div>
        <div id = "picture-one">
            <img src="/images/TheCodeIsFuture.jpg" alt="code-img">
        </div>
        <div id="picture-two">
            <img src="/images/RubiksCube.png" alt="cube">
        </div>
    </div>
    <div class = "second-screen">
        <div class = "second-title-module">
            <div id = "second-title">
                <button id = "about-title">ABOUT ME</button>
            </div>
        </div>
        <div id = "about-me">
            <p>
                Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
            </p>
        </div>
        <div id = "about-me-pic">
            <img src="/images/RoadMap.png">
        </div>
    </div>
    <div class = "third-screen">
        <div id = "projects-title">

        </div>
        <div id = "first-project">

        </div>
        <div id = "second-project">

        </div>
        <div id = "third-project">

        </div>
        <div id="project-img">
            <img src="">
        </div>
    </div>
    <div class = "fourth-screen">
        <div id = "contact-title">

        </div>
        <div id = "linkedIn-img">
            <img src="">
        </div>
        <div id = "twitter-img">
            <img src="">
        </div>
        <div id = "email-img">
            <img src="">
        </div>
        <div id = "email-text">

        </div>
        <div id = "github-img">
        <img src="">
        </div>
    </div>
    <div class = "fifth-screen">
        <div id ="contact-title">

        </div>
    </div>
</main>
<?php require('template/footer.phtml');
?>
