<!DOCTYPE html>
<html lang="eng">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Personal portfolio">
        <meta name="author" content="Vadims Seimanovs">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-grid.css" rel="stylesheet">
        <link href="/css/bootstrap-reboot.css" rel="stylesheet">
        <link href="/css/my-styles.css" rel="stylesheet">
        <link href="/css/mobile.css" rel="stylesheet">
        <link href="/css/tablet.css" rel="stylesheet">
        <link rel="icon" href="/images/RubiksCube.png">
        <title><?php echo $view->pageTitle; ?></title>
        <script type="text/javascript" src="https://platform.linkedin.com/badges/js/profile.js" async defer></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/github-cards/latest/widget.js" async defer></script>
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script>
    </head>
</html>