<!DOCTYPE html>
<html lang="eng">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Personal portfolio">
        <meta name="author" content="Vadims Seimanovs">
        <link href="/css/bootstrap.css" rel="stylesheet">
        <link href="/css/bootstrap-grid.css" rel="stylesheet">
        <link href="/css/bootstrap-reboot.css" rel="stylesheet">
        <link href="/css/my-styles.css" rel="stylesheet">
        <title><?php echo $view->pageTitle; ?></title>
    </head>
</html>